name: CI

on: [push]

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar
      - name: Build and push Auth
        uses: docker/build-push-action@v4
        with:
          context: ./auth
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coffee-auth