name: CI

on: [push]

env:
  REGISTRY: ghcr.io
  USER: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage --publishImage
